spring:
  session:
    store-type: redis
    redis:
      namespace: medilabo:sessions
      flush-mode: on_save
  data:
    redis:
      host: localhost
      port: 6379

spring.session.timeout: 30m

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        same-site: Lax

